# Generated by Django 5.2 on 2025-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('driving_license_no', models.CharField(max_length=50)),
                ('engine_no', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('vehicle_use', models.CharField(max_length=50)),
                ('driving_license_valid', models.BooleanField()),
                ('commercial_permit', models.BooleanField()),
                ('policy_no', models.CharField(max_length=50)),
                ('policy_start_date', models.DateField()),
                ('policy_End_date', models.DateField()),
                ('type_of_incident', models.CharField(max_length=100)),
                ('damage_severity', models.CharField(max_length=50)),
                ('drinking', models.BooleanField()),
                ('Police_reports', models.BooleanField()),
                ('eyewitness', models.BooleanField()),
                ('past_claims', models.BooleanField()),
                ('substantial_proofs', models.BooleanField()),
                ('principal_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claim_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_age', models.IntegerField()),
                ('price_of_vehicle', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(max_length=500)),
                ('Police_Report', models.CharField(max_length=500)),
            ],
        ),
    ]
